//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagementSystem
{
    partial class DashboardForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(DashboardForm));
            this.panelSidebar = new System.Windows.Forms.Panel();
            this.btnLogout_Sidebar = new System.Windows.Forms.Button();
            this.btnEditStudent_Sidebar = new System.Windows.Forms.Button();
            this.btnViewStudent_Sidebar = new System.Windows.Forms.Button();
            this.btnAddStudent_Sidebar = new System.Windows.Forms.Button();
            this.btnDashboard_Sidebar = new System.Windows.Forms.Button();
            this.panelCentral = new System.Windows.Forms.Panel();
            this.referencePanel = new System.Windows.Forms.Panel();
            this.labelWelcome = new System.Windows.Forms.Label();
            this.btnViewStudent_Central = new System.Windows.Forms.Button();
            this.btnEditStudent_Central = new System.Windows.Forms.Button();
            this.btnAddStudent_Central = new System.Windows.Forms.Button();
            this.labelSchoolName = new System.Windows.Forms.Label();
            this.panelSidebar.SuspendLayout();
            this.panelCentral.SuspendLayout();
            this.SuspendLayout();
            // 
            // panelSidebar
            // 
            this.panelSidebar.BackColor = System.Drawing.Color.LightCoral;
            this.panelSidebar.Controls.Add(this.btnLogout_Sidebar);
            this.panelSidebar.Controls.Add(this.btnEditStudent_Sidebar);
            this.panelSidebar.Controls.Add(this.btnViewStudent_Sidebar);
            this.panelSidebar.Controls.Add(this.btnAddStudent_Sidebar);
            this.panelSidebar.Controls.Add(this.btnDashboard_Sidebar);
            this.panelSidebar.Dock = System.Windows.Forms.DockStyle.Left;
            this.panelSidebar.Location = new System.Drawing.Point(0, 0);
            this.panelSidebar.Margin = new System.Windows.Forms.Padding(4);
            this.panelSidebar.Name = "panelSidebar";
            this.panelSidebar.Size = new System.Drawing.Size(200, 724);
            this.panelSidebar.TabIndex = 0;
            // 
            // btnLogout_Sidebar
            // 
            this.btnLogout_Sidebar.BackColor = System.Drawing.Color.IndianRed;
            this.btnLogout_Sidebar.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.btnLogout_Sidebar.Font = new System.Drawing.Font("Arial Rounded MT Bold", 10.2F);
            this.btnLogout_Sidebar.ForeColor = System.Drawing.Color.White;
            this.btnLogout_Sidebar.Location = new System.Drawing.Point(0, 675);
            this.btnLogout_Sidebar.Margin = new System.Windows.Forms.Padding(4);
            this.btnLogout_Sidebar.Name = "btnLogout_Sidebar";
            this.btnLogout_Sidebar.Size = new System.Drawing.Size(200, 49);
            this.btnLogout_Sidebar.TabIndex = 4;
            this.btnLogout_Sidebar.Text = "Logout";
            this.btnLogout_Sidebar.UseVisualStyleBackColor = false;
            this.btnLogout_Sidebar.Click += new System.EventHandler(this.btnLogout_Sidebar_Click);
            // 
            // btnEditStudent_Sidebar
            // 
            this.btnEditStudent_Sidebar.BackColor = System.Drawing.Color.IndianRed;
            this.btnEditStudent_Sidebar.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnEditStudent_Sidebar.Font = new System.Drawing.Font("Arial Rounded MT Bold", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnEditStudent_Sidebar.ForeColor = System.Drawing.Color.White;
            this.btnEditStudent_Sidebar.Location = new System.Drawing.Point(0, 147);
            this.btnEditStudent_Sidebar.Margin = new System.Windows.Forms.Padding(4);
            this.btnEditStudent_Sidebar.Name = "btnEditStudent_Sidebar";
            this.btnEditStudent_Sidebar.Size = new System.Drawing.Size(200, 49);
            this.btnEditStudent_Sidebar.TabIndex = 3;
            this.btnEditStudent_Sidebar.Text = "Edit Student Detail";
            this.btnEditStudent_Sidebar.UseVisualStyleBackColor = false;
            this.btnEditStudent_Sidebar.Click += new System.EventHandler(this.btnEditStudent_Sidebar_Click);
            // 
            // btnViewStudent_Sidebar
            // 
            this.btnViewStudent_Sidebar.BackColor = System.Drawing.Color.IndianRed;
            this.btnViewStudent_Sidebar.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnViewStudent_Sidebar.Font = new System.Drawing.Font("Arial Rounded MT Bold", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnViewStudent_Sidebar.ForeColor = System.Drawing.Color.White;
            this.btnViewStudent_Sidebar.Location = new System.Drawing.Point(0, 98);
            this.btnViewStudent_Sidebar.Margin = new System.Windows.Forms.Padding(4);
            this.btnViewStudent_Sidebar.Name = "btnViewStudent_Sidebar";
            this.btnViewStudent_Sidebar.Size = new System.Drawing.Size(200, 49);
            this.btnViewStudent_Sidebar.TabIndex = 2;
            this.btnViewStudent_Sidebar.Text = "View Student Detail";
            this.btnViewStudent_Sidebar.UseVisualStyleBackColor = false;
            this.btnViewStudent_Sidebar.Click += new System.EventHandler(this.btnViewStudent_Sidebar_Click);
            // 
            // btnAddStudent_Sidebar
            // 
            this.btnAddStudent_Sidebar.BackColor = System.Drawing.Color.IndianRed;
            this.btnAddStudent_Sidebar.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnAddStudent_Sidebar.Font = new System.Drawing.Font("Arial Rounded MT Bold", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnAddStudent_Sidebar.ForeColor = System.Drawing.Color.White;
            this.btnAddStudent_Sidebar.Location = new System.Drawing.Point(0, 49);
            this.btnAddStudent_Sidebar.Margin = new System.Windows.Forms.Padding(4);
            this.btnAddStudent_Sidebar.Name = "btnAddStudent_Sidebar";
            this.btnAddStudent_Sidebar.Size = new System.Drawing.Size(200, 49);
            this.btnAddStudent_Sidebar.TabIndex = 1;
            this.btnAddStudent_Sidebar.Text = "Add Student Detail";
            this.btnAddStudent_Sidebar.UseVisualStyleBackColor = false;
            this.btnAddStudent_Sidebar.Click += new System.EventHandler(this.btnAddStudent_Sidebar_Click);
            // 
            // btnDashboard_Sidebar
            // 
            this.btnDashboard_Sidebar.BackColor = System.Drawing.Color.IndianRed;
            this.btnDashboard_Sidebar.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnDashboard_Sidebar.Font = new System.Drawing.Font("Arial Rounded MT Bold", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnDashboard_Sidebar.ForeColor = System.Drawing.Color.White;
            this.btnDashboard_Sidebar.Location = new System.Drawing.Point(0, 0);
            this.btnDashboard_Sidebar.Margin = new System.Windows.Forms.Padding(4);
            this.btnDashboard_Sidebar.Name = "btnDashboard_Sidebar";
            this.btnDashboard_Sidebar.Size = new System.Drawing.Size(200, 49);
            this.btnDashboard_Sidebar.TabIndex = 0;
            this.btnDashboard_Sidebar.Text = "Dashboard";
            this.btnDashboard_Sidebar.UseVisualStyleBackColor = false;
            this.btnDashboard_Sidebar.Click += new System.EventHandler(this.btnDashboard_Sidebar_Click);
            // 
            // panelCentral
            // 
            this.panelCentral.BackColor = System.Drawing.Color.MistyRose;
            this.panelCentral.Controls.Add(this.referencePanel);
            this.panelCentral.Controls.Add(this.labelWelcome);
            this.panelCentral.Controls.Add(this.btnViewStudent_Central);
            this.panelCentral.Controls.Add(this.btnEditStudent_Central);
            this.panelCentral.Controls.Add(this.btnAddStudent_Central);
            this.panelCentral.Controls.Add(this.labelSchoolName);
            this.panelCentral.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panelCentral.Location = new System.Drawing.Point(200, 0);
            this.panelCentral.Margin = new System.Windows.Forms.Padding(4);
            this.panelCentral.Name = "panelCentral";
            this.panelCentral.Padding = new System.Windows.Forms.Padding(27, 25, 27, 25);
            this.panelCentral.Size = new System.Drawing.Size(1023, 724);
            this.panelCentral.TabIndex = 1;
            // 
            // referencePanel
            // 
            this.referencePanel.BackColor = System.Drawing.Color.Transparent;
            this.referencePanel.Location = new System.Drawing.Point(30, 98);
            this.referencePanel.Name = "referencePanel";
            this.referencePanel.Size = new System.Drawing.Size(960, 622);
            this.referencePanel.TabIndex = 5;
            this.referencePanel.Visible = false;
            // 
            // labelWelcome
            // 
            this.labelWelcome.AutoSize = true;
            this.labelWelcome.Font = new System.Drawing.Font("Arial Rounded MT Bold", 20F);
            this.labelWelcome.ForeColor = System.Drawing.Color.Brown;
            this.labelWelcome.Location = new System.Drawing.Point(31, 98);
            this.labelWelcome.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.labelWelcome.Name = "labelWelcome";
            this.labelWelcome.Size = new System.Drawing.Size(199, 39);
            this.labelWelcome.TabIndex = 1;
            this.labelWelcome.Text = "Dashboard";
            // 
            // btnViewStudent_Central
            // 
            this.btnViewStudent_Central.BackColor = System.Drawing.Color.Transparent;
            this.btnViewStudent_Central.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnViewStudent_Central.BackgroundImage")));
            this.btnViewStudent_Central.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Zoom;
            this.btnViewStudent_Central.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnViewStudent_Central.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnViewStudent_Central.ForeColor = System.Drawing.Color.Transparent;
            this.btnViewStudent_Central.Location = new System.Drawing.Point(689, 266);
            this.btnViewStudent_Central.Margin = new System.Windows.Forms.Padding(4);
            this.btnViewStudent_Central.Name = "btnViewStudent_Central";
            this.btnViewStudent_Central.Size = new System.Drawing.Size(293, 139);
            this.btnViewStudent_Central.TabIndex = 3;
            this.btnViewStudent_Central.UseVisualStyleBackColor = false;
            this.btnViewStudent_Central.Click += new System.EventHandler(this.btnViewStudent_Central_Click);
            // 
            // btnEditStudent_Central
            // 
            this.btnEditStudent_Central.BackColor = System.Drawing.Color.Transparent;
            this.btnEditStudent_Central.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnEditStudent_Central.BackgroundImage")));
            this.btnEditStudent_Central.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Zoom;
            this.btnEditStudent_Central.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnEditStudent_Central.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnEditStudent_Central.ForeColor = System.Drawing.Color.White;
            this.btnEditStudent_Central.Location = new System.Drawing.Point(363, 266);
            this.btnEditStudent_Central.Margin = new System.Windows.Forms.Padding(4);
            this.btnEditStudent_Central.Name = "btnEditStudent_Central";
            this.btnEditStudent_Central.Size = new System.Drawing.Size(287, 139);
            this.btnEditStudent_Central.TabIndex = 4;
            this.btnEditStudent_Central.UseVisualStyleBackColor = false;
            this.btnEditStudent_Central.Click += new System.EventHandler(this.btnEditStudent_Central_Click);
            // 
            // btnAddStudent_Central
            // 
            this.btnAddStudent_Central.BackColor = System.Drawing.Color.Transparent;
            this.btnAddStudent_Central.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnAddStudent_Central.BackgroundImage")));
            this.btnAddStudent_Central.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Zoom;
            this.btnAddStudent_Central.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnAddStudent_Central.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnAddStudent_Central.ForeColor = System.Drawing.Color.Transparent;
            this.btnAddStudent_Central.Location = new System.Drawing.Point(33, 266);
            this.btnAddStudent_Central.Margin = new System.Windows.Forms.Padding(4);
            this.btnAddStudent_Central.Name = "btnAddStudent_Central";
            this.btnAddStudent_Central.Size = new System.Drawing.Size(290, 139);
            this.btnAddStudent_Central.TabIndex = 2;
            this.btnAddStudent_Central.UseVisualStyleBackColor = false;
            this.btnAddStudent_Central.Click += new System.EventHandler(this.btnAddStudent_Central_Click);
            // 
            // labelSchoolName
            // 
            this.labelSchoolName.AutoSize = true;
            this.labelSchoolName.Font = new System.Drawing.Font("Arial Rounded MT Bold", 28F);
            this.labelSchoolName.ForeColor = System.Drawing.Color.Brown;
            this.labelSchoolName.Location = new System.Drawing.Point(138, 25);
            this.labelSchoolName.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.labelSchoolName.Name = "labelSchoolName";
            this.labelSchoolName.Size = new System.Drawing.Size(666, 54);
            this.labelSchoolName.TabIndex = 0;
            this.labelSchoolName.Text = "School Management System";
            // 
            // DashboardForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(120F, 120F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Dpi;
            this.ClientSize = new System.Drawing.Size(1223, 724);
            this.Controls.Add(this.panelCentral);
            this.Controls.Add(this.panelSidebar);
            this.Margin = new System.Windows.Forms.Padding(4);
            this.Name = "DashboardForm";
            this.Text = "Dashboard";
            this.panelSidebar.ResumeLayout(false);
            this.panelCentral.ResumeLayout(false);
            this.panelCentral.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel panelSidebar;
        private System.Windows.Forms.Button btnLogout_Sidebar;
        private System.Windows.Forms.Button btnEditStudent_Sidebar;
        private System.Windows.Forms.Button btnViewStudent_Sidebar;
        private System.Windows.Forms.Button btnAddStudent_Sidebar;
        private System.Windows.Forms.Button btnDashboard_Sidebar;
        private System.Windows.Forms.Panel panelCentral;
        private System.Windows.Forms.Label labelSchoolName;
        private System.Windows.Forms.Button btnViewStudent_Central;
        private System.Windows.Forms.Button btnEditStudent_Central;
        private System.Windows.Forms.Button btnAddStudent_Central;
        private System.Windows.Forms.Panel referencePanel;
        private System.Windows.Forms.Label labelWelcome;
    }
}